### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by cchun01** [cchun01/Potion#4]
**Background**
About Us page that includes information on the creators of Potion.

**To Do**
- Create the front-end of the About Us page
- Add descriptions and names of each member
- Include photos of each member 

**Figma Mockup**
<img width="357" alt="Screen Shot 2022-02-02 at 1 39 14 PM" src="https://user-images.githubusercontent.com/70447594/152241673-f7c6a22e-11d4-494f-82b5-c262f5be7fd7.png">

**Hours Expected:** 3 hours
**Actual Hours:** 1.5 hours

**Comment by cchun01** [comment]
Create the UI for the about page. Have descriptions of every member of the group and their portraits included.

**Comment by alexa-nov** [comment]
**Hours Actual:** 1.5 hours
